name: Stdlib Daily 2

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: coq8.17
            coq_version: 8.17
            ocaml_version: 4.13-flambda
          - branch: coq8.18
            coq_version: 8.18
            ocaml_version: 4.13-flambda
          - branch: coq8.19
            coq_version: 8.19
            ocaml_version: 4.13-flambda
          - branch: coq8.20
            coq_version: 8.20
            ocaml_version: 4.13-flambda
          - branch: coqdev
            coq_version: dev
            ocaml_version: 4.13-flambda

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'coq-tactician'
          ref: ${{ matrix.branch }}
      - uses: coq-community/docker-coq-action@v1.2.3
        with:
          opam_file: 'coq-tactician.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          install: |
            startGroup "Install dependencies"
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam pin add -n -y -k path coq-tactician coq-tactician/
              opam update -y
              opam install -y -j 2 coq-tactician
            endGroup
          script: |
            startGroup "Build"
              yes n | tactician inject
              opam reinstall coq-stdlib --yes
            endGroup
          uninstall: |
            startGroup "Uninstallation test"
              opam remove coq-stdlib --yes
            endGroup
